### ISSUE TITLE
need help, problem with installing

### ISSUE THREAD

**Issue by naito78** [Pauloo27/tiktok-live#1]
I just follow the steps and something wrong came up like this.

```
C:\Users\Administrator\tiktok-live>npm install
npm WARN tiktoklive@1.0.0 No repository field.
npm WARN tiktoklive@1.0.0 license should be a valid SPDX license expression
```

What does this mean and how can i solve this?

And i tried to save a live stream but failed.
```

`C:\Users\Administrator\tiktok-live>node index.js https://v.douyin.com/JR2Lbpe/
URL > https://v.douyin.com/JR2Lbpe
ID > JR2Lbpe
(node:9640) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at C:\Users\Administrator\tiktok-live\index.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```

what should i do?

**Comment by Pauloo27** [comment]
Hello.
I just fixed both problems, I recommend you to delete the repository and reinstall it again.

I tested it using `https://vm.tiktok.com/` URLs, I don't know if it will work with `v.douyin.com`.

Also, I don't know if the README explain what that project does. It download the live to a FLV file but to do that you need to keep the process running. It will not download the whole live, it just download the live from when you started the download until you close the process.
If that is what you need, I think it will work for you.

**Comment by naito78** [comment]
Thanks for the help. 
I tried again but still the same.

```
C:\Users\Administrator\tiktok-live>npm install
npm WARN tiktoklive@1.0.0 No repository field.
```

Yeah i just want to download the live. I think this project is what i need.
I tested it using `vt.tiktok.com/AGTpVg/` url, but still didn't work.

Thank you again.

**Comment by vnnegt** [comment]
@Pauloo27 I receive the same errors

example usage: `node index.js https://vm.tiktok.com/<ID>/`

rejection:

> (node:2564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /home/lhayman/proj/node/tiktok-live/index.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Pauloo27** [comment]
@vnnegt I've pushed a commit that show all found URLs, can you post the output? I think the string that I'm using to find the live url only works in my country

**Comment by vnnegt** [comment]
sure!

@Pauloo27 

```
[
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg',
  'https://m.tiktok.com/share/live/6850913385375091461/?language=en&u_code=db5ij5a7imil46&utm_campaign=client_share&utm_medium=ios&user_id=6799077948579955717&tt_from=copy&utm_source=copy',
  'https://sf-tb-sg.ibytedtos.com/obj/ttfe-malisg/tiktok/modernizr-custom.min.js',
  'https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js',
  'https://s0.ipstatp.com/growth/fe_sdk/reportsdk/sdk.js?t=1595102847000',
  'https://s0.ipstatp.com/static_magic/pgc/tech/collect/collect.js',
  'https://mon-va.byteoversea.com/slardar/sdk.js?bid=tiktok_reflow_m',
  '//s0.ipstatp.com',
  '//s16.tiktokcdn.com',
  '//v16.tiktokcdn.com',
  '//p16-va.tiktokcdn.com',
  '//www.google-analytics.com',
  '//stats.g.doubleclick.net',
  '//s16.tiktokcdn.com/musical/resource/wap/static/image/logo_144c91a.png?v=2',
  '//s16.tiktokcdn.com/tiktok/falcon/static/css/42.bundle.8cffb872.css',
  'https://m.tiktok.com',
  'https://www.amazon.com/dp/B0117U0G3M/',
  'https://www.tiktok.com/download-link/af/com.zhiliaoapp.musically',
  'https://www.tiktok.com/download-link/af/id835599320',
  'https://www.tiktok.com/safety/resources/covid-19',
  'https://m.tiktok.com/share/live/6850913385375091461/?language=en&u_code=db5ij5a7imil46&utm_campaign=client_share&utm_medium=ios&user_id=6799077948579955717&tt_from=copy&utm_source=copy',
  'http://pull-hls-f1-ab.tiktokcdn.com/stage/stream-2989349282351153185/playlist.m3u8',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_100x100.jpeg',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_720x720.jpeg',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg',
  'https://p16-va-default.akamaized.net/obj/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg)',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg',
  'https://p16-va-tiktok.ibyteimg.com/img/musically-maliva-obj/e52e5f0212f7841248f477452678d8ab~c5_1080x1080.jpeg);background-size:cover;background-position:center',
  'https://pull-hls-f1-ab.tiktokcdn.com/stage/stream-2989349282351153185/playlist.m3u8',
  '//s16.tiktokcdn.com/tiktok/falcon/static/js/8cffb872.js',
  '//s16.tiktokcdn.com/tiktok/falcon/static/js/455f20bf.js',
  '//s16.tiktokcdn.com/tiktok/falcon/static/js/1beffc76.js',
  '//s16.tiktokcdn.com/tiktok/falcon/static/js/51e93692.js'
]
(node:3877) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /home/lhayman/proj/node/tiktok-live/index.js:37:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Pauloo27** [comment]
@vnnegt can you try it now?

**Comment by vnnegt** [comment]
> @vnnegt can you try it now?

it works!

thanks a bunch!!

**Comment by Pauloo27** [comment]
No problem, thanks for the help
